"""Initial migration

Revision ID: 98fa557179df
Revises: 
Create Date: 2025-06-16 00:21:49.345712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fa557179df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personnel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'personnels', ['personnel_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('personnel_id')

    # ### end Alembic commands ###
