"""Migrated routes

Revision ID: c8e5f0f1033c
Revises: 
Create Date: 2025-05-23 09:05:08.699756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e5f0f1033c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('camera_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cam_name', sa.String(length=200), nullable=False),
    sa.Column('feed_src', sa.String(length=200), nullable=True),
    sa.Column('x1', sa.Integer(), nullable=True),
    sa.Column('y1', sa.Integer(), nullable=True),
    sa.Column('x2', sa.Integer(), nullable=True),
    sa.Column('y2', sa.Integer(), nullable=True),
    sa.Column('x3', sa.Integer(), nullable=True),
    sa.Column('y3', sa.Integer(), nullable=True),
    sa.Column('x4', sa.Integer(), nullable=True),
    sa.Column('y4', sa.Integer(), nullable=True),
    sa.Column('x5', sa.Integer(), nullable=True),
    sa.Column('y5', sa.Integer(), nullable=True),
    sa.Column('x6', sa.Integer(), nullable=True),
    sa.Column('y6', sa.Integer(), nullable=True),
    sa.Column('x7', sa.Integer(), nullable=True),
    sa.Column('y7', sa.Integer(), nullable=True),
    sa.Column('x8', sa.Integer(), nullable=True),
    sa.Column('y8', sa.Integer(), nullable=True),
    sa.Column('cam_is_active', sa.Boolean(), nullable=True),
    sa.Column('gender_detection', sa.Boolean(), nullable=True),
    sa.Column('face_detection', sa.Boolean(), nullable=True),
    sa.Column('face_capture', sa.Boolean(), nullable=True),
    sa.Column('id_card_detection', sa.Boolean(), nullable=True),
    sa.Column('uniform_detection', sa.Boolean(), nullable=True),
    sa.Column('shoes_detection', sa.Boolean(), nullable=True),
    sa.Column('ciggerate_detection', sa.Boolean(), nullable=True),
    sa.Column('sit_detection', sa.Boolean(), nullable=True),
    sa.Column('cam_start', sa.String(length=200), nullable=True),
    sa.Column('cam_stop', sa.String(length=200), nullable=True),
    sa.Column('attendance_time_start', sa.String(length=200), nullable=True),
    sa.Column('attendance_time_end', sa.String(length=200), nullable=True),
    sa.Column('leaving_time_start', sa.String(length=200), nullable=True),
    sa.Column('leaving_time_end', sa.String(length=200), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('role_camera', sa.String(length=10), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counted_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('male_entries', sa.Integer(), nullable=True),
    sa.Column('female_entries', sa.Integer(), nullable=True),
    sa.Column('unknown_gender_entries', sa.Integer(), nullable=True),
    sa.Column('staff_entries', sa.Integer(), nullable=True),
    sa.Column('intern_entries', sa.Integer(), nullable=True),
    sa.Column('unknown_role_entries', sa.Integer(), nullable=True),
    sa.Column('people_exits', sa.Integer(), nullable=True),
    sa.Column('people_inside', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('personnel_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('presence_status', sa.String(length=10), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('timer', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_settings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_timer')
    op.drop_table('personnel_images')
    op.drop_table('personnel_entries')
    op.drop_table('personnels')
    op.drop_table('counted_instances')
    op.drop_table('divisions')
    op.drop_table('camera_settings')
    op.drop_table('company')
    op.drop_table('users')
    # ### end Alembic commands ###
